// <auto-generated />
using System;
using ConsoleScraper;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConsoleScraper.Migrations
{
    [DbContext(typeof(StockContext))]
    partial class StockContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065");

            modelBuilder.Entity("ConsoleScraper.StockContext+Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AvgVol3m");

                    b.Property<string>("Currency");

                    b.Property<DateTime>("Date");

                    b.Property<string>("LastPrice");

                    b.Property<string>("MarketCap");

                    b.Property<string>("MarketTime");

                    b.Property<string>("PercentChange");

                    b.Property<string>("Shares");

                    b.Property<string>("Symbol");

                    b.Property<string>("Volume");

                    b.HasKey("Id");

                    b.ToTable("Stocks");
                });
#pragma warning restore 612, 618
        }
    }
}
